import type { App, TFile } from 'obsidian';
import { normalizePath, parseYaml, stringifyYaml } from 'obsidian';

import { resolveSprintProfile } from '../domain/SprintSettings';
import {
  addDays,
  getCurrentSprintStart,
  getLocalDate,
  getSprintEnd,
  getWeekStart,
} from '../domain/SprintSchedule';
import type { SprintProfile, SprintSettings } from '../domain/types';
import { SPRINT_BASES_VIEW_TYPE, SPRINT_VELOCITY_VIEW_TYPE } from './SprintBasesView';

export interface SprintBaseGenerationResult {
  created: number;
  skipped: number;
  profilesGenerated: number;
}

interface BaseDefinition {
  path: string;
  folder: string;
  content: string;
}

interface SampleNote {
  path: string;
  content: string;
  sprintName?: string;
  removeDefaultOwner?: boolean;
}

type SampleVersion = 'legacy' | 'current';
type SprintTaskScope = 'current' | 'next';

const MANAGED_START = '<!-- sprint-managed-start -->';
const MANAGED_END = '<!-- sprint-managed-end -->';
const GENERATED_FILE_MARKER = '<!-- sprint-generated-file -->';
export const SPRINT_SUMMARY_FILENAME = 'Sprint Summary.md';
export type SprintSummaryWriteAction = 'create' | 'unchanged' | 'preserve';

export function getSprintSummaryWriteAction(
  existing: string | null,
  generated: string,
): SprintSummaryWriteAction {
  if (existing === null) return 'create';
  return existing === generated ? 'unchanged' : 'preserve';
}

function isAlreadyExistsError(error: unknown): boolean {
  return error instanceof Error && /already exists/i.test(error.message);
}

function normalizeFolder(value: string): string {
  return normalizePath(value.trim()).replace(/^\/+|\/+$/g, '');
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

function baseFolder(path: string): string {
  return path.split('/').slice(0, -1).join('/');
}

function basePath(value: string): string {
  return normalizePath(value.trim()).replace(/^\/+/, '');
}

function frontmatterNote(frontmatter: string[], body: string): string {
  return [
    '---',
    ...frontmatter,
    '---',
    '',
    body.trim(),
    '',
  ].join('\n');
}

function baseConfig(
  folder: string,
  properties: Record<string, string>,
  views: string[],
  formulas: Record<string, string> = {},
): string {
  const propertyLines = Object.entries(properties).flatMap(([key, displayName]) => [
    `  ${key}:`,
    `    displayName: ${yamlString(displayName)}`,
  ]);
  const formulaLines = Object.entries(formulas).flatMap(([key, formula]) => [
    `  ${key}: ${formula}`,
  ]);

  return [
    'filters:',
    '  and:',
    `    - ${yamlString(`file.inFolder(${yamlString(folder)})`)}`,
    '    - "file.ext == \\"md\\""',
    'properties:',
    ...propertyLines,
    ...(formulaLines.length > 0 ? ['formulas:', ...formulaLines] : []),
    'views:',
    ...views,
    '',
  ].join('\n');
}

function sprintInstructions(settings: SprintSettings, profiles = settings.profiles): string {
  const profileLines = profiles.map((profile) => (
    `- ${profile.name || profile.id}: root \`${profile.rootFolder}\`, Tasks Base \`${profile.tasksBasePath}\`, Sprints Base \`${profile.sprintsBasePath}\`, Projects Base \`${profile.projectsBasePath}\``
  ));

  return [
    '# Sprint AI Instructions',
    '',
    'These instructions are generated by the Sprint Obsidian plugin for local AI coding and note-management tools.',
    '',
    '## Role',
    '',
    'Help the user manage projects, backlog tasks, sprint planning, execution, reviews, and retrospectives inside this Obsidian vault. The user remains the decision maker.',
    '',
    '## Sources of Truth',
    '',
    '- Sprint settings and generated sprint notes are authoritative for cadence, sprint dates, sprint numbering, lifecycle status, and rollover.',
    '- Do not create a competing sprint cadence or independently renumber generated sprints.',
    '- Task notes live in each profile\'s `Tasks` folder unless the vault documents a different convention.',
    '- Sprint notes live in each profile\'s `Sprints` folder.',
    '- Project notes live in each profile\'s `Projects` folder.',
    '- `Tasks.base`, `Sprints.base`, and `Projects.base` live directly in each profile root by default.',
    '- Existing notes and Base files define the vault\'s actual property names and conventions. Inspect them before changing files.',
    '',
    '## Workspace',
    '',
    ...profileLines,
    '',
    '## Standard Metadata',
    '',
    'Task notes use numeric `estimate`, date `due`, boolean `in progress`, boolean `is done`, boolean `archived`, and link-list `project` and `sprint` properties. Project notes use boolean `in progress`, boolean `is done`, and boolean `hidden`. They may also use `priority` or other vault-specific properties. Sprint notes use `sprint number`, `start date`, `end date`, `sprint status`, `review`, and `retrospective`.',
    '',
    '## Operating Rules',
    '',
    '- Use the configured Sprint workspace before editing tasks or projects.',
    '- Identify the current sprint from `sprint status: current`; do not infer it from a filename alone.',
    '- Represent task state consistently: Not started means both state booleans are false; In progress means `in progress` is true and `is done` is false; Done means `is done` is true and `in progress` is false.',
    '- Set `archived: true` only when the user wants a task removed from sprint boards while retaining it in the Tasks view and vault history.',
    '- Set a project\'s `hidden` property only to control its visibility on sprint boards; do not confuse hidden with project completion.',
    '- When creating a task, place it in the profile `Tasks` folder and link it to an existing project and sprint when those are known.',
    '- Store `project` and `sprint` as lists of Obsidian links, matching the conventions in existing generated task notes.',
    '- For broad or destructive changes, summarize the proposed file changes and ask for confirmation first.',
    '- Assign tasks to existing generated sprint notes by updating the `sprint` property.',
    '- Mark tasks complete only when the user says the work is complete or available evidence clearly establishes completion.',
    '- Never claim a task, sprint, project, Base, or setting was changed unless the corresponding vault write succeeded.',
    '',
  ].join('\n');
}

export function sprintSkillContent(
  settings: SprintSettings,
  profiles = settings.profiles,
  customInstructions = settings.skillCustomInstructions['sprint-vault'] ?? '',
): string {
  const custom = customInstructions.trim();
  return [
    '---',
    'name: sprint-vault',
    'description: Manage Sprint-generated Obsidian agile project notes, tasks, sprints, Bases, and reviews in this vault.',
    '---',
    '',
    GENERATED_FILE_MARKER,
    '',
    sprintInstructions(settings, profiles),
    ...(custom ? [
      '## Vault-specific instructions',
      '',
      custom,
      '',
    ] : []),
  ].join('\n');
}

function tableView(name: string, order: string[]): string[] {
  return [
    '  - type: table',
    `    name: ${yamlString(name)}`,
    '    order:',
    ...order.map((property) => `      - ${property}`),
  ];
}

function sprintOverviewView(profileId: string): string[] {
  return [
    `  - type: ${SPRINT_BASES_VIEW_TYPE}`,
    '    name: "Sprint overview"',
    '    filters:',
    '      or:',
    '        - note["sprint status"] == "current"',
    '        - note["sprint status"] == "next"',
    '        - note["sprint status"] == "last"',
    '    groupBy:',
    '      property: sprint status',
    '      direction: ASC',
    `    sprintProfile: ${yamlString(profileId)}`,
    '    itemType: "sprint"',
    '    layout: board',
    '    showCompleted: true',
  ];
}

function sprintView(
  profileId: string,
  name: string,
  layout: 'board' | 'list' | 'kanban' | 'planner',
  showCompleted: boolean,
  sprintScope?: SprintTaskScope,
): string[] {
  return [
    `  - type: ${SPRINT_BASES_VIEW_TYPE}`,
    `    name: ${yamlString(name)}`,
    '    filters:',
    '      and:',
    '        - note.archived != true',
    ...(sprintScope ? [`        - formula.is_${sprintScope}_sprint`] : []),
    ...(layout === 'kanban' ? [
      '    groupBy:',
      '      property: formula.task_state',
      '      direction: ASC',
    ] : []),
    '    order:',
    '      - file.name',
    ...(layout === 'planner' ? ['      - note.project'] : []),
    '      - note.estimate',
    '      - note.due',
    ...(!sprintScope && layout !== 'planner' ? ['      - note.sprint'] : []),
    `    sprintProfile: ${yamlString(profileId)}`,
    ...(sprintScope ? [`    sprintScope: ${yamlString(sprintScope)}`] : []),
    `    layout: ${yamlString(layout)}`,
    `    showCompleted: ${showCompleted}`,
  ];
}

function managedContent(content: string): string {
  return `${MANAGED_START}\n${content.trim()}\n${MANAGED_END}\n`;
}

function replaceManagedSection(existing: string, content: string): string {
  const next = managedContent(content);
  const start = existing.indexOf(MANAGED_START);
  const end = existing.indexOf(MANAGED_END);
  if (start === -1 || end === -1 || end < start) {
    return `${existing.trimEnd()}\n\n${next}`;
  }
  return `${existing.slice(0, start)}${next}${existing.slice(end + MANAGED_END.length).replace(/^\n/, '')}`;
}

function taskBaseProperties(): Record<string, string> {
  return {
    'file.name': 'Task',
    'formula.task_state': 'State',
    'note.project': 'Project',
    'note.sprint': 'Sprint',
    'note.estimate': 'Estimate',
    'note.due': 'Due',
    'note.in progress': 'In progress',
    'note.is done': 'Done',
    'note.archived': 'Archived',
  };
}

function tasksBaseContent(
  settings: SprintSettings,
  profile: SprintProfile,
): string {
  const resolved = resolveSprintProfile(settings, profile);
  const root = normalizeFolder(resolved.rootFolder);
  return baseConfig(
    `${root}/Tasks`,
    taskBaseProperties(),
    [
      ...sprintView(resolved.id, 'Sprint board', 'kanban', true),
      ...sprintView(resolved.id, 'Sprint planner', 'planner', true),
      ...tableView('Tasks', [
        'file.name',
        'formula.task_state',
        'note.project',
        'note.sprint',
        'note.estimate',
        'note.due',
        'note.in progress',
        'note.is done',
        'note.archived',
      ]),
      ...sprintView(resolved.id, 'Current sprint', 'kanban', true, 'current'),
      ...sprintView(resolved.id, 'Next sprint', 'kanban', true, 'next'),
    ],
    {
      task_state: 'if(note["is done"], "Done", if(note["in progress"], "In progress", "Not started"))',
      is_current_sprint: 'note.sprint.filter(value.asFile().properties["sprint status"] == "current").length > 0',
      is_next_sprint: 'note.sprint.filter(value.asFile().properties["sprint status"] == "next").length > 0',
    },
  );
}

type BaseRecord = Record<string, unknown>;

function asRecord(value: unknown): BaseRecord | null {
  return value && typeof value === 'object' && !Array.isArray(value)
    ? value as BaseRecord
    : null;
}

function appendFilter(view: BaseRecord, filter: string): boolean {
  const filters = asRecord(view.filters);
  if (!filters) {
    view.filters = { and: [filter] };
    return true;
  }
  const and = filters.and;
  if (Array.isArray(and)) {
    if (and.includes(filter)) return false;
    and.unshift(filter);
    return true;
  }
  view.filters = { and: [filter, filters] };
  return true;
}

function appendOrder(view: BaseRecord, property: string): boolean {
  if (!Array.isArray(view.order) || view.order.includes(property)) return false;
  view.order.push(property);
  return true;
}

function migrateBaseContent(
  content: string,
  mutate: (base: BaseRecord) => boolean,
): string {
  try {
    const base = asRecord(parseYaml(content));
    if (!base || !mutate(base)) return content;
    return stringifyYaml(base);
  } catch {
    return content;
  }
}

export function migrateBaseFolderContent(content: string, folder: string): string {
  return migrateBaseContent(content, (base) => {
    const filters = asRecord(base.filters);
    if (!filters || !Array.isArray(filters.and)) return false;
    const index = filters.and.findIndex((filter) => (
      typeof filter === 'string' && filter.startsWith('file.inFolder(')
    ));
    if (index === -1) return false;
    const expected = `file.inFolder(${JSON.stringify(folder)})`;
    if (filters.and[index] === expected) return false;
    filters.and[index] = expected;
    return true;
  });
}

export function migrateTasksBaseContent(content: string, profileId: string): string {
  return migrateBaseContent(content, (base) => {
    let changed = false;
    const properties = asRecord(base.properties);
    if (properties && !properties['note.due']) {
      properties['note.due'] = { displayName: 'Due' };
      changed = true;
    }
    if (properties && !properties['note.archived']) {
      properties['note.archived'] = { displayName: 'Archived' };
      changed = true;
    }
    if (!Array.isArray(base.views)) return changed;
    const hasPlanner = base.views.some((candidate) => (
      asRecord(candidate)?.name === 'Sprint planner'
    ));
    if (!hasPlanner) {
      base.views.push({
        type: SPRINT_BASES_VIEW_TYPE,
        name: 'Sprint planner',
        filters: { and: ['note.archived != true'] },
        order: ['file.name', 'note.project', 'note.estimate', 'note.due'],
        sprintProfile: profileId,
        layout: 'planner',
        showCompleted: true,
      });
      changed = true;
    }
    for (const candidate of base.views) {
      const view = asRecord(candidate);
      if (!view) continue;
      if (view.type === 'table' && view.name === 'Tasks') {
        changed = appendOrder(view, 'note.due') || changed;
        changed = appendOrder(view, 'note.archived') || changed;
        continue;
      }
      if (view.type !== SPRINT_BASES_VIEW_TYPE || view.sprintProfile !== profileId) continue;
      changed = appendFilter(view, 'note.archived != true') || changed;
      if (!Array.isArray(view.order)) {
        const legacyCardProperties = [1, 2, 3]
          .map((position) => view[`cardProperty${position}`])
          .filter((property): property is string => typeof property === 'string');
        const defaultCardProperties = [
          'note.estimate',
          ...(view.name === 'Sprint board' ? ['note.sprint'] : []),
        ];
        view.order = ['file.name', ...(
          legacyCardProperties.length > 0 ? legacyCardProperties : defaultCardProperties
        )];
        changed = true;
      }
      const oldDefaultOrder = view.name === 'Sprint board'
        ? ['file.name', 'note.estimate', 'note.sprint']
        : view.name === 'Current sprint' || view.name === 'Next sprint'
          ? ['file.name', 'note.estimate']
          : null;
      if (
        oldDefaultOrder
        && Array.isArray(view.order)
        && view.order.length === oldDefaultOrder.length
        && view.order.every((property, index) => property === oldDefaultOrder[index])
      ) {
        view.order.splice(2, 0, 'note.due');
        changed = true;
      }
      for (const position of [1, 2, 3]) {
        const key = `cardProperty${position}`;
        if (view[key] === undefined) continue;
        delete view[key];
        changed = true;
      }
    }
    return changed;
  });
}

export function migrateProjectsBaseContent(content: string): string {
  return migrateBaseContent(content, (base) => {
    let changed = false;
    const properties = asRecord(base.properties);
    if (properties && !properties['note.hidden']) {
      properties['note.hidden'] = { displayName: 'Hidden' };
      changed = true;
    }
    if (!Array.isArray(base.views)) return changed;
    for (const candidate of base.views) {
      const view = asRecord(candidate);
      if (view?.type === 'table' && view.name === 'Projects') {
        changed = appendOrder(view, 'note.hidden') || changed;
      }
    }
    return changed;
  });
}

function projectsBaseContent(
  settings: SprintSettings,
  profile: SprintProfile,
  includeOwner = false,
): string {
  const resolved = resolveSprintProfile(settings, profile);
  const root = normalizeFolder(resolved.rootFolder);
  return baseConfig(
    `${root}/Projects`,
    {
      'file.name': 'Project',
      'formula.project_state': 'State',
      'note.in progress': 'In progress',
      'note.is done': 'Done',
      'note.hidden': 'Hidden',
      ...(includeOwner ? { 'note.owner': 'Owner' } : {}),
      'note.priority': 'Priority',
      'note.due': 'Due',
    },
    [
      ...tableView('Projects', [
        'file.name',
        'formula.project_state',
        'note.in progress',
        'note.is done',
        'note.hidden',
        ...(includeOwner ? ['note.owner'] : []),
        'note.priority',
        'note.due',
      ]),
    ],
    {
      project_state: 'if(note["is done"], "Done", if(note["in progress"], "In progress", "Not started"))',
    },
  );
}

function definitionsForProfile(settings: SprintSettings, profile: SprintProfile): BaseDefinition[] {
  const resolved = resolveSprintProfile(settings, profile);
  const root = normalizeFolder(resolved.rootFolder);
  if (!root) throw new Error(`Set a Sprint folder for ${resolved.name || 'this workspace'}.`);

  const tasksBase = basePath(resolved.tasksBasePath || `${root}/Tasks.base`);
  const sprintsBase = basePath(resolved.sprintsBasePath || `${root}/Sprints.base`);
  const projectsBase = basePath(resolved.projectsBasePath || `${root}/Projects.base`);

  return [
    {
      path: tasksBase,
      folder: `${root}/Tasks`,
      content: tasksBaseContent(settings, profile),
    },
    {
      path: sprintsBase,
      folder: `${root}/Sprints`,
      content: baseConfig(
        `${root}/Sprints`,
        {
          'file.name': 'Sprint',
          'note.sprint number': 'Number',
          'note.start date': 'Start',
          'note.end date': 'End',
          'note.sprint status': 'Status',
          'note.review': 'Review',
          'note.retrospective': 'Retrospective',
        },
        [
          ...sprintOverviewView(resolved.id),
          '  - type: table',
          '    name: "Active sprints"',
          '    filters:',
          '      or:',
          '        - note["sprint status"] == "current"',
          '        - note["sprint status"] == "next"',
          '        - note["sprint status"] == "last"',
          '    order:',
          ...[
            'file.name',
            'sprint status',
            'start date',
            'end date',
            'formula.planned',
            'formula.velocity',
            'review',
            'retrospective',
          ].map((property) => `      - ${property}`),
          '    sort:',
          '      - property: start date',
          '        direction: DESC',
          `  - type: ${SPRINT_VELOCITY_VIEW_TYPE}`,
          '    name: "Velocity"',
          `    sprintProfile: ${yamlString(resolved.id)}`,
          '  - type: table',
          '    name: "All sprints"',
          '    order:',
          ...[
            'file.name',
            'sprint status',
            'start date',
            'end date',
            'formula.nth_sprint',
            'formula.planned',
            'formula.velocity',
            'review',
            'retrospective',
          ].map((property) => `      - ${property}`),
          '    sort:',
          '      - property: start date',
          '        direction: DESC',
          '    columnSize:',
          '      formula.nth_sprint: 100',
          '      formula.velocity: 86',
        ],
        {
          nth_sprint: 'number(file.name.split(" ")[1])',
          velocity: 'file.backlinks.filter(value.asFile().properties["is done"]).map(value.asFile().properties.estimate).reduce(acc + value, 0)',
          planned: 'file.backlinks.map(value.asFile().properties.estimate).reduce(acc + value, 0)',
        },
      ),
    },
    {
      path: projectsBase,
      folder: `${root}/Projects`,
      content: projectsBaseContent(settings, profile),
    },
  ];
}

export class SprintBaseGenerator {
  constructor(
    private readonly app: App,
    private readonly getToday: () => string = getLocalDate,
  ) {}

  async generate(settings: SprintSettings): Promise<SprintBaseGenerationResult> {
    const result: SprintBaseGenerationResult = {
      created: 0,
      skipped: 0,
      profilesGenerated: 0,
    };

    for (const profile of settings.profiles.filter((candidate) => candidate.enabled)) {
      const root = normalizeFolder(profile.rootFolder);
      const workspaceExisted = root !== ''
        && this.app.vault.getAbstractFileByPath(root) !== null;
      const definitions = definitionsForProfile(settings, profile);
      for (const definition of definitions) {
        await this.withContext(`Migrate Base folder for ${definition.path}`, () => (
          this.migrateExistingBase(
            definition.path,
            (content) => migrateBaseFolderContent(content, definition.folder),
          )
        ));
      }
      await this.withContext(`Migrate Tasks Base for ${profile.name || profile.id}`, () => (
        this.migrateTasksBase(settings, profile)
      ));
      await this.withContext(`Migrate Projects Base for ${profile.name || profile.id}`, () => (
        this.migrateProjectsBase(settings, profile)
      ));
      for (const definition of definitions) {
        await this.withContext(`Create Base ${definition.path}`, async () => {
          await this.ensureFolder(definition.folder);
          await this.ensureFolder(baseFolder(definition.path));
          if (this.app.vault.getAbstractFileByPath(definition.path)) {
            result.skipped += 1;
            return;
          }
          const created = await this.createBaseFile(definition.path, definition.content);
          if (created) result.created += 1;
          else result.skipped += 1;
        });
      }
      if (profile.samplesInitialized !== true && !workspaceExisted) {
        await this.withContext(`Create samples for ${profile.name || profile.id}`, () => (
          this.writeSampleNotes(settings, profile)
        ));
      }
      await this.withContext(`Create dashboard for ${profile.name || profile.id}`, () => (
        this.writeDashboard(settings, profile)
      ));
      await this.withContext(`Write AI instructions for ${profile.name || profile.id}`, () => (
        this.writeProfileAgentInstructions(settings, profile)
      ));
      result.profilesGenerated += 1;
    }
    await this.withContext('Write vault-root AI skills', () => this.writeVaultRootSkills(settings));
    await this.withContext('Update vault-root AI instructions', () => (
      settings.generateVaultRootInstructions
        ? this.writeVaultRootAgentInstructions(settings)
        : this.removeVaultRootAgentInstructions()
    ));
    await this.withContext('Write Obsidian property types', () => this.writePropertyTypes());

    return result;
  }

  async resetProfileRoot(settings: SprintSettings, profileId: string): Promise<void> {
    const profile = settings.profiles.find((candidate) => candidate.id === profileId);
    if (!profile) throw new Error('Sprint workspace not found.');
    const root = normalizeFolder(profile.rootFolder);
    if (!root) throw new Error(`Set a Sprint folder for ${profile.name || 'this workspace'} before resetting.`);
    const existing = this.app.vault.getAbstractFileByPath(root);
    if (existing) await this.app.fileManager.trashFile(existing);
  }

  private async migrateTasksBase(settings: SprintSettings, profile: SprintProfile): Promise<void> {
    const resolved = resolveSprintProfile(settings, profile);
    await this.migrateExistingBase(
      basePath(resolved.tasksBasePath),
      (content) => migrateTasksBaseContent(content, resolved.id),
    );
  }

  private async migrateProjectsBase(settings: SprintSettings, profile: SprintProfile): Promise<void> {
    const resolved = resolveSprintProfile(settings, profile);
    const path = basePath(resolved.projectsBasePath);
    const existing = this.app.vault.getFileByPath(path);
    if (!existing) return;
    const candidate = await this.app.vault.read(existing);
    if (candidate === projectsBaseContent(settings, profile, true)) {
      await this.app.vault.process(existing, (current) => (
        current === projectsBaseContent(settings, profile, true)
          ? projectsBaseContent(settings, profile)
          : current
      ));
    }
    await this.migrateExistingBase(path, migrateProjectsBaseContent);
  }

  private async migrateExistingBase(
    path: string,
    migrate: (content: string) => string,
  ): Promise<void> {
    const existing = this.app.vault.getFileByPath(path);
    if (!existing) return;
    const candidate = await this.app.vault.read(existing);
    if (migrate(candidate) === candidate) return;
    await this.app.vault.process(existing, migrate);
  }

  private async ensureFolder(folder: string): Promise<void> {
    let current = '';
    for (const segment of normalizePath(folder).split('/').filter(Boolean)) {
      current = current ? `${current}/${segment}` : segment;
      const existing = this.app.vault.getAbstractFileByPath(current);
      if (existing) continue;
      try {
        await this.app.vault.createFolder(current);
      } catch (error) {
        if (!isAlreadyExistsError(error) && !this.app.vault.getAbstractFileByPath(current)) {
          throw error;
        }
      }
    }
  }

  private async writeProfileAgentInstructions(
    settings: SprintSettings,
    profile: SprintProfile,
  ): Promise<void> {
    const root = normalizeFolder(profile.rootFolder);
    if (!root) return;
    const instructions = sprintInstructions(settings, [profile]);
    await this.writeManagedFile(`${root}/AGENTS.md`, instructions);
    await this.writeManagedFile(`${root}/CLAUDE.md`, instructions);
    await this.removeOwnedSkillFile(`${root}/.codex/skills/sprint/SKILL.md`);
    await this.removeOwnedSkillFile(`${root}/.agents/skills/sprint/SKILL.md`);
    await this.removeOwnedSkillFile(`${root}/.claude/skills/sprint/SKILL.md`);
  }

  private async writeVaultRootSkills(settings: SprintSettings): Promise<void> {
    const content = sprintSkillContent(settings);
    await this.removeOwnedSkillFile('.codex/skills/sprint/SKILL.md');
    await this.writeOwnedFile('.agents/skills/sprint/SKILL.md', content);
    await this.writeOwnedFile('.claude/skills/sprint/SKILL.md', content);
  }

  private async writeVaultRootAgentInstructions(settings: SprintSettings): Promise<void> {
    await this.removeLegacyVaultRootSkills();
    await this.writeManagedFile('AGENTS.md', sprintInstructions(settings));
    await this.writeManagedFile('CLAUDE.md', sprintInstructions(settings));
  }

  private async removeVaultRootAgentInstructions(): Promise<void> {
    await this.removeManagedFile('AGENTS.md');
    await this.removeManagedFile('CLAUDE.md');
    await this.removeLegacyVaultRootSkills();
  }

  private async removeLegacyVaultRootSkills(): Promise<void> {
    await this.removeOwnedSkillFile('.codex/skills/sprint/SKILL.md');
  }

  private async writePropertyTypes(): Promise<void> {
    const path = normalizePath(`${this.app.vault.configDir}/types.json`);
    const existing = await this.app.vault.adapter.exists(path)
      ? await this.app.vault.adapter.read(path)
      : '{}';
    const parsed = this.parseJsonObject(existing);
    const types = this.parseJsonObject(parsed.types);
    Object.assign(types, {
      estimate: 'number',
      'in progress': 'checkbox',
      'is done': 'checkbox',
      project: 'multitext',
      sprint: 'multitext',
      priority: 'number',
      due: 'date',
      archived: 'checkbox',
      hidden: 'checkbox',
      'due date': 'date',
    });
    parsed.types = types;
    await this.app.vault.adapter.write(path, `${JSON.stringify(parsed, null, 2)}\n`);
  }

  private async createBaseFile(path: string, content: string): Promise<boolean> {
    try {
      await this.app.vault.create(path, content);
      return true;
    } catch (error) {
      if (!isAlreadyExistsError(error) && !this.app.vault.getAbstractFileByPath(path)) {
        throw error;
      }
      return false;
    }
  }

  private async withContext<T>(label: string, operation: () => Promise<T>): Promise<T> {
    try {
      return await operation();
    } catch (error) {
      const detail = error instanceof Error ? error.message : String(error);
      throw new Error(`${label} failed: ${detail}`, { cause: error });
    }
  }

  private parseJsonObject(value: unknown): Record<string, unknown> {
    if (typeof value === 'string') {
      try {
        const parsed = JSON.parse(value) as unknown;
        return this.parseJsonObject(parsed);
      } catch {
        return {};
      }
    }
    return value && typeof value === 'object' && !Array.isArray(value)
      ? { ...value as Record<string, unknown> }
      : {};
  }

  private async writeSampleNotes(settings: SprintSettings, profile: SprintProfile): Promise<void> {
    const resolved = resolveSprintProfile(settings, profile);
    const root = normalizeFolder(resolved.rootFolder);
    if (!root) return;
    const today = this.getToday();
    const durationWeeks = Math.min(8, Math.max(1, Math.round(resolved.durationWeeks)));
    const anchorDate = resolved.anchorDate || getWeekStart(today, resolved.startDay);
    const currentStart = getCurrentSprintStart(anchorDate, durationWeeks, today);

    const previousSamples = new Map(
      this.sampleNotes(root, resolved.namingFormat, 'legacy', currentStart, durationWeeks)
        .map((note) => [note.path, note]),
    );
    for (const note of this.sampleNotes(
      root,
      resolved.namingFormat,
      'current',
      currentStart,
      durationWeeks,
    )) {
      const existing = this.app.vault.getFileByPath(note.path);
      if (existing) {
        const previous = previousSamples.get(note.path);
        let migrated = false;
        if (previous && previous.content !== note.content) {
          const candidate = await this.app.vault.read(existing);
          if (candidate === previous.content) {
            await this.app.vault.process(existing, (current) => {
              if (current !== previous.content) return current;
              migrated = true;
              return note.content;
            });
          }
        }
        if (!migrated) {
          if (note.sprintName) await this.assignSampleSprintIfMissing(existing, note.sprintName);
          if (note.removeDefaultOwner) await this.removeSampleDefaultOwner(existing);
        }
        continue;
      }
      await this.writeFile(note.path, note.content);
    }
  }

  private sampleNotes(
    root: string,
    namingFormat: string,
    version: SampleVersion,
    currentStart: string,
    durationWeeks: number,
  ): SampleNote[] {
    const sprintName = (number: number): string => (
      namingFormat.replaceAll('{number}', String(number)).trim() || `Sprint ${number}`
    );
    const sprintOne = sprintName(1);
    const sprintTwo = sprintName(2);
    const nextStart = addDays(currentStart, durationWeeks * 7);
    const sprintProperty = (name: string): string[] => version === 'current'
      ? ['sprint:', `  - "[[${name}]]"`]
      : [];
    const dueProperty = (date: string): string[] => version === 'current'
      ? [`due: ${date}`]
      : [];
    const notes: SampleNote[] = [
      {
        path: `${root}/Projects/Welcome to Agile PM.md`,
        content: frontmatterNote(
          [
            'priority: 1',
            'in progress: true',
            'is done: false',
            ...(version === 'legacy' ? ['owner: "You"'] : []),
          ],
          [
            '# Welcome to Agile PM',
            '',
            'Use this project to learn the workflow. Projects collect related task notes and help you see what each sprint supports.',
            '',
            'Try opening the Projects Base, then replace this tutorial project after you create your first real project.',
          ].join('\n'),
        ),
        removeDefaultOwner: true,
      },
      {
        path: `${root}/Projects/Sprint system setup.md`,
        content: frontmatterNote(
          [
            'priority: 2',
            'in progress: false',
            'is done: false',
            ...(version === 'legacy' ? ['owner: "You"'] : []),
          ],
          [
            '# Sprint system setup',
            '',
            'This sample project groups the tutorial tasks that explain how to plan, execute, and review sprint work.',
          ].join('\n'),
        ),
        removeDefaultOwner: true,
      },
      {
        path: `${root}/Tasks/Review the Agile PM dashboard.md`,
        content: frontmatterNote(
          [
            'estimate: 1',
            ...dueProperty(currentStart),
            'in progress: false',
            'is done: false',
            ...(version === 'current' ? ['archived: false'] : []),
            'project:',
            '  - "[[Welcome to Agile PM]]"',
            ...sprintProperty(sprintOne),
          ],
          [
            '# Review the Agile PM dashboard',
            '',
            'Open the dashboard note at the top of this folder and inspect the current tasks, Velocity chart, current sprint scope, and Projects view.',
          ].join('\n'),
        ),
        sprintName: sprintOne,
      },
      {
        path: `${root}/Tasks/Add your first real task.md`,
        content: frontmatterNote(
          [
            'estimate: 2',
            ...dueProperty(addDays(currentStart, 1)),
            'in progress: false',
            'is done: false',
            ...(version === 'current' ? ['archived: false'] : []),
            'project:',
            '  - "[[Welcome to Agile PM]]"',
            ...sprintProperty(sprintOne),
          ],
          [
            '# Add your first real task',
            '',
            version === 'current'
              ? 'Create a task note in the Tasks folder. Give it an estimate, connect it to a project, and assign it to a generated sprint when you are ready to plan it.'
              : 'Create a task note in the Tasks folder. Give it an estimate, connect it to a project, and leave `sprint` empty until you are ready to plan it.',
          ].join('\n'),
        ),
        sprintName: sprintOne,
      },
      {
        path: `${root}/Tasks/Plan work into the current sprint.md`,
        content: frontmatterNote(
          [
            'estimate: 3',
            ...dueProperty(addDays(currentStart, 2)),
            'in progress: true',
            'is done: false',
            ...(version === 'current' ? ['archived: false'] : []),
            'project:',
            '  - "[[Sprint system setup]]"',
            ...sprintProperty(sprintOne),
          ],
          [
            '# Plan work into the current sprint',
            '',
            'Use the Tasks Base to assign a task to the generated current sprint. Sprint creates sprint notes and keeps their status metadata synchronized.',
          ].join('\n'),
        ),
        sprintName: sprintOne,
      },
      {
        path: `${root}/Tasks/Mark a task complete.md`,
        content: frontmatterNote(
          [
            'estimate: 1',
            ...dueProperty(addDays(currentStart, 3)),
            'in progress: false',
            'is done: true',
            ...(version === 'current' ? ['archived: false'] : []),
            'project:',
            '  - "[[Sprint system setup]]"',
            ...sprintProperty(sprintOne),
          ],
          [
            '# Mark a task complete',
            '',
            'Set `is done` to true when the task is finished. Completed estimates contribute to the Velocity view in the Sprints Base.',
          ].join('\n'),
        ),
        sprintName: sprintOne,
      },
      {
        path: `${root}/Tasks/Write a sprint review.md`,
        content: frontmatterNote(
          [
            'estimate: 2',
            ...dueProperty(getSprintEnd(currentStart, durationWeeks)),
            'in progress: false',
            'is done: false',
            ...(version === 'current' ? ['archived: false'] : []),
            'project:',
            '  - "[[Sprint system setup]]"',
            ...sprintProperty(sprintOne),
          ],
          [
            '# Write a sprint review',
            '',
            'At the end of a sprint, summarize outcomes in the generated sprint note. Keep retrospectives concrete and action-oriented.',
          ].join('\n'),
        ),
        sprintName: sprintOne,
      },
    ];

    if (version === 'current') {
      notes.push(
        {
          path: `${root}/Tasks/Plan next week's sprint.md`,
          content: frontmatterNote(
            [
              'estimate: 2',
              `due: ${addDays(nextStart, 1)}`,
              'in progress: false',
              'is done: false',
              'archived: false',
              'project:',
              '  - "[[Sprint system setup]]"',
              ...sprintProperty(sprintTwo),
            ],
            [
              "# Plan next week's sprint",
              '',
              'Review what was learned in Sprint 1, confirm the next priorities, and keep the Sprint 2 scope small enough to finish.',
            ].join('\n'),
          ),
          sprintName: sprintTwo,
        },
        {
          path: `${root}/Tasks/Continue the Agile PM workflow.md`,
          content: frontmatterNote(
            [
              'estimate: 3',
              `due: ${addDays(nextStart, 3)}`,
              'in progress: false',
              'is done: false',
              'archived: false',
              'project:',
              '  - "[[Welcome to Agile PM]]"',
              ...sprintProperty(sprintTwo),
            ],
            [
              '# Continue the Agile PM workflow',
              '',
              'Carry one useful improvement into Sprint 2 and update its task state on the Sprint board as the work progresses.',
            ].join('\n'),
          ),
          sprintName: sprintTwo,
        },
      );
    }

    return notes;
  }

  private async assignSampleSprintIfMissing(file: TFile, sprintName: string): Promise<void> {
    const frontmatter = this.app.metadataCache.getFileCache(file)?.frontmatter;
    if (!frontmatter || frontmatter.sprint !== undefined) return;
    await this.app.fileManager.processFrontMatter(file, (properties) => {
      const target = properties as Record<string, unknown>;
      if (target.sprint === undefined) target.sprint = [`[[${sprintName}]]`];
    });
  }

  private async removeSampleDefaultOwner(file: TFile): Promise<void> {
    const frontmatter = this.app.metadataCache.getFileCache(file)?.frontmatter;
    if (frontmatter?.owner !== 'You') return;
    await this.app.fileManager.processFrontMatter(file, (properties) => {
      const target = properties as Record<string, unknown>;
      if (target.owner === 'You') delete target.owner;
    });
  }

  private async writeDashboard(settings: SprintSettings, profile: SprintProfile): Promise<void> {
    const resolved = resolveSprintProfile(settings, profile);
    const root = normalizeFolder(resolved.rootFolder);
    if (!root) return;

    await this.ensureFolder(root);
    const dashboardPath = `${root}/${SPRINT_SUMMARY_FILENAME}`;
    const legacyTitle = root.split('/').at(-1) || resolved.name || 'Sprint';
    const legacyDashboardPath = `${root}/${legacyTitle}.md`;
    const legacyDashboard = this.app.vault.getFileByPath(legacyDashboardPath);
    if (
      legacyDashboard
      && legacyDashboardPath !== dashboardPath
      && !this.app.vault.getAbstractFileByPath(dashboardPath)
    ) {
      await this.app.fileManager.renameFile(legacyDashboard, dashboardPath);
    }

    const content = [
      '## Current Tasks',
      '',
      `![[${resolved.tasksBasePath}#Current sprint]]`,
      '',
      '---',
      '',
      '## Velocity',
      '',
      `![[${resolved.sprintsBasePath}#Velocity]]`,
      '',
      '---',
      '',
      '## Projects',
      '',
      `![[${resolved.projectsBasePath}#Projects]]`,
      '',
    ].join('\n');

    const existingDashboard = this.app.vault.getFileByPath(dashboardPath);
    const existingContent = existingDashboard
      ? await this.app.vault.read(existingDashboard)
      : null;
    const action = getSprintSummaryWriteAction(existingContent, content);
    if (action === 'create') {
      await this.writeFile(dashboardPath, content);
      return;
    }
    if (action === 'preserve') {
      console.warn(`[Sprint] Skipped user-edited Sprint Summary: ${dashboardPath}`);
    }
  }

  private getFrontmatter(file: TFile): Record<string, unknown> {
    return { ...(this.app.metadataCache.getFileCache(file)?.frontmatter ?? {}) };
  }

  private async writeManagedFile(path: string, content: string, initialContent = ''): Promise<void> {
    const existing = this.app.vault.getFileByPath(path);
    if (!existing) {
      await this.writeFile(path, `${initialContent}${managedContent(content)}`);
      return;
    }
    const candidate = await this.app.vault.read(existing);
    if (!candidate.includes(MANAGED_START) || !candidate.includes(MANAGED_END)) {
      console.warn(`[Sprint] Skipped existing AI instruction file not managed by Sprint: ${path}`);
      return;
    }
    let managed = false;
    await this.app.vault.process(existing, (current) => {
      if (!current.includes(MANAGED_START) || !current.includes(MANAGED_END)) return current;
      managed = true;
      return replaceManagedSection(current, content);
    });
    if (!managed) {
      console.warn(`[Sprint] Skipped existing AI instruction file not managed by Sprint: ${path}`);
    }
  }

  private async removeManagedFile(path: string): Promise<void> {
    const existing = this.app.vault.getFileByPath(path);
    if (!existing) return;
    const candidate = await this.app.vault.read(existing);
    if (!candidate.includes(MANAGED_START) || !candidate.includes(MANAGED_END)) return;
    let removed = false;
    let empty = false;
    await this.app.vault.process(existing, (current) => {
      const start = current.indexOf(MANAGED_START);
      const end = current.indexOf(MANAGED_END);
      if (start === -1 || end === -1 || end < start) return current;
      removed = true;
      const remaining = `${current.slice(0, start)}${current.slice(end + MANAGED_END.length)}`.trim();
      empty = remaining.length === 0;
      return empty ? '' : `${remaining}\n`;
    });
    if (removed && empty) await this.app.fileManager.trashFile(existing);
  }

  private async writeOwnedFile(path: string, content: string): Promise<void> {
    await this.ensureFolder(baseFolder(path));
    const existing = this.app.vault.getFileByPath(path);
    if (!existing) {
      await this.writeFile(path, content);
      return;
    }
    const candidate = await this.app.vault.read(existing);
    if (!candidate.includes(GENERATED_FILE_MARKER)) {
      console.warn(`[Sprint] Skipped existing AI skill file not managed by Sprint: ${path}`);
      return;
    }
    let owned = false;
    await this.app.vault.process(existing, (current) => {
      if (!current.includes(GENERATED_FILE_MARKER)) return current;
      owned = true;
      return content;
    });
    if (!owned) {
      console.warn(`[Sprint] Skipped existing AI skill file not managed by Sprint: ${path}`);
    }
  }

  private async removeOwnedSkillFile(path: string): Promise<void> {
    const existing = this.app.vault.getFileByPath(path);
    if (!existing) return;
    const current = await this.app.vault.read(existing);
    const isSprintGenerated = current.includes(GENERATED_FILE_MARKER) || (
      current.includes('name: sprint-vault')
      && current.includes('These instructions are generated by the Sprint Obsidian plugin')
    );
    if (isSprintGenerated) await this.app.fileManager.trashFile(existing);
  }

  private async writeFile(path: string, content: string): Promise<void> {
    await this.ensureFolder(baseFolder(path));
    const existing = this.app.vault.getFileByPath(path);
    if (existing) {
      await this.app.vault.process(existing, () => content);
      return;
    }
    try {
      await this.app.vault.create(path, content);
    } catch (error) {
      if (!isAlreadyExistsError(error)) throw error;
      const raced = this.app.vault.getFileByPath(path);
      if (!raced) throw error;
      await this.app.vault.process(raced, () => content);
    }
  }
}
