import type { App, TFile } from 'obsidian';
import { normalizePath } from 'obsidian';

import { resolveSprintProfile } from '../domain/SprintSettings';
import type { SprintProfile, SprintSettings } from '../domain/types';
import { SPRINT_BASES_VIEW_TYPE, SPRINT_VELOCITY_VIEW_TYPE } from './SprintBasesView';

export interface SprintBaseGenerationResult {
  created: number;
  skipped: number;
  profilesGenerated: number;
}

interface BaseDefinition {
  path: string;
  folder: string;
  content: string;
}

interface SprintSummary {
  name: string;
  path: string;
  startDate: string | null;
  endDate: string | null;
  status: string | null;
}

interface TaskSummary {
  name: string;
  path: string;
  sprint: unknown;
  estimate: number;
  done: boolean;
}

interface SampleNote {
  path: string;
  content: string;
}

const MANAGED_START = '<!-- sprint-managed-start -->';
const MANAGED_END = '<!-- sprint-managed-end -->';
const GENERATED_FILE_MARKER = '<!-- sprint-generated-file -->';

function isAlreadyExistsError(error: unknown): boolean {
  return error instanceof Error && /already exists/i.test(error.message);
}

function normalizeFolder(value: string): string {
  return normalizePath(value.trim()).replace(/^\/+|\/+$/g, '');
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

function baseFolder(path: string): string {
  return path.split('/').slice(0, -1).join('/');
}

function basePath(value: string): string {
  return normalizePath(value.trim()).replace(/^\/+/, '');
}

function frontmatterNote(frontmatter: string[], body: string): string {
  return [
    '---',
    ...frontmatter,
    '---',
    '',
    body.trim(),
    '',
  ].join('\n');
}

function baseConfig(
  folder: string,
  properties: Record<string, string>,
  views: string[],
  formulas: Record<string, string> = {},
): string {
  const propertyLines = Object.entries(properties).flatMap(([key, displayName]) => [
    `  ${key}:`,
    `    displayName: ${yamlString(displayName)}`,
  ]);
  const formulaLines = Object.entries(formulas).flatMap(([key, formula]) => [
    `  ${key}: ${formula}`,
  ]);

  return [
    'filters:',
    '  and:',
    `    - ${yamlString(`file.inFolder(${yamlString(folder)})`)}`,
    '    - "file.ext == \\"md\\""',
    'properties:',
    ...propertyLines,
    ...(formulaLines.length > 0 ? ['formulas:', ...formulaLines] : []),
    'views:',
    ...views,
    '',
  ].join('\n');
}

function sprintInstructions(settings: SprintSettings, profiles = settings.profiles): string {
  const profileLines = profiles.map((profile) => (
    `- ${profile.name || profile.id}: root \`${profile.rootFolder}\`, Tasks Base \`${profile.tasksBasePath}\`, Sprints Base \`${profile.sprintsBasePath}\`, Projects Base \`${profile.projectsBasePath}\``
  ));

  return [
    '# Sprint AI Instructions',
    '',
    'These instructions are generated by the Sprint Obsidian plugin for local AI coding and note-management tools.',
    '',
    '## Role',
    '',
    'Help the user manage projects, backlog tasks, sprint planning, execution, reviews, and retrospectives inside this Obsidian vault. The user remains the decision maker.',
    '',
    '## Sources of Truth',
    '',
    '- Sprint settings and generated sprint notes are authoritative for cadence, sprint dates, sprint numbering, lifecycle status, and rollover.',
    '- Do not create a competing sprint cadence or independently renumber generated sprints.',
    '- Task notes live in each profile\'s `Tasks` folder unless the vault documents a different convention.',
    '- Sprint notes live in each profile\'s `Sprints` folder.',
    '- Project notes live in each profile\'s `Projects` folder.',
    '- Existing notes and Base files define the vault\'s actual property names and conventions. Inspect them before changing files.',
    '',
    '## Profiles',
    '',
    ...profileLines,
    '',
    '## Standard Metadata',
    '',
    'Task notes commonly use `estimate`, `in progress`, `is done`, `project`, and `sprint` properties. Sprint notes use `sprint number`, `start date`, `end date`, `sprint status`, `review`, and `retrospective`.',
    '',
    '## Operating Rules',
    '',
    '- Identify the relevant profile before editing tasks or projects.',
    '- Identify the current sprint from `sprint status: current`; do not infer it from a filename alone.',
    '- For broad or destructive changes, summarize the proposed file changes and ask for confirmation first.',
    '- Assign tasks to existing generated sprint notes by updating the `sprint` property.',
    '- Mark tasks complete only when the user says the work is complete or available evidence clearly establishes completion.',
    '- Never claim a task, sprint, project, Base, or setting was changed unless the corresponding vault write succeeded.',
    '',
  ].join('\n');
}

function skillInstructions(settings: SprintSettings, profiles = settings.profiles): string {
  return [
    '---',
    'name: sprint-vault',
    'description: Manage Sprint-generated Obsidian agile project notes, tasks, sprints, Bases, and reviews in this vault.',
    '---',
    '',
    GENERATED_FILE_MARKER,
    '',
    sprintInstructions(settings, profiles),
  ].join('\n');
}

function tableView(name: string, order: string[]): string[] {
  return [
    '  - type: table',
    `    name: ${yamlString(name)}`,
    '    order:',
    ...order.map((property) => `      - ${property}`),
  ];
}

function sprintOverviewView(profileId: string): string[] {
  return [
    `  - type: ${SPRINT_BASES_VIEW_TYPE}`,
    '    name: "Sprint overview"',
    '    filters:',
    '      or:',
    '        - note["sprint status"] == "current"',
    '        - note["sprint status"] == "next"',
    '        - note["sprint status"] == "last"',
    '    groupBy:',
    '      property: sprint status',
    '      direction: ASC',
    `    sprintProfile: ${yamlString(profileId)}`,
    '    layout: board',
    '    showCompleted: true',
  ];
}

function sprintView(profileId: string, name: string, layout: 'board' | 'list' | 'kanban'): string[] {
  return [
    `  - type: ${SPRINT_BASES_VIEW_TYPE}`,
    `    name: ${yamlString(name)}`,
    ...(layout === 'kanban' ? [
      '    groupBy:',
      '      property: formula.task_state',
      '      direction: ASC',
    ] : []),
    `    sprintProfile: ${yamlString(profileId)}`,
    `    layout: ${yamlString(layout)}`,
    '    showCompleted: false',
  ];
}

function linkTo(path: string, label: string): string {
  return `[[${path.replace(/\.md$/, '')}|${label}]]`;
}

function readDate(value: unknown): string | null {
  return typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value) ? value : null;
}

function sprintReferences(value: unknown, sprintName: string): boolean {
  const values = Array.isArray(value) ? value : [value];
  return values.some((entry) => {
    if (typeof entry !== 'string') return false;
    const normalized = entry.trim().replace(/^\[\[/, '').replace(/\]\]$/, '').split('|')[0] ?? '';
    return normalized === sprintName || normalized.endsWith(`/${sprintName}`);
  });
}

function isTaskDone(frontmatter: Record<string, unknown>): boolean {
  return frontmatter['is done'] === true;
}

function numericEstimate(value: unknown): number {
  return typeof value === 'number' && Number.isFinite(value) ? Math.max(0, value) : 0;
}

function managedContent(content: string): string {
  return `${MANAGED_START}\n${content.trim()}\n${MANAGED_END}\n`;
}

function replaceManagedSection(existing: string, content: string): string {
  const next = managedContent(content);
  const start = existing.indexOf(MANAGED_START);
  const end = existing.indexOf(MANAGED_END);
  if (start === -1 || end === -1 || end < start) {
    return `${existing.trimEnd()}\n\n${next}`;
  }
  return `${existing.slice(0, start)}${next}${existing.slice(end + MANAGED_END.length).replace(/^\n/, '')}`;
}

function taskBaseProperties(): Record<string, string> {
  return {
    'file.name': 'Task',
    'formula.task_state': 'State',
    'note.project': 'Project',
    'note.sprint': 'Sprint',
    'note.estimate': 'Estimate',
    'note.in progress': 'In progress',
    'note.is done': 'Done',
  };
}

function tasksBaseContent(
  settings: SprintSettings,
  profile: SprintProfile,
  includeSprintBoard: boolean,
): string {
  const resolved = resolveSprintProfile(settings, profile);
  const root = normalizeFolder(resolved.rootFolder);
  return baseConfig(
    `${root}/Tasks`,
    taskBaseProperties(),
    [
      ...tableView('Tasks', [
        'file.name',
        'formula.task_state',
        'note.project',
        'note.sprint',
        'note.estimate',
        'note.in progress',
        'note.is done',
      ]),
      ...(includeSprintBoard ? sprintView(resolved.id, 'Sprint board', 'kanban') : []),
    ],
    {
      task_state: 'if(note["is done"], "Done", if(note["in progress"], "In progress", "Not started"))',
    },
  );
}

function standaloneSprintBoardContent(settings: SprintSettings, profile: SprintProfile): string {
  const resolved = resolveSprintProfile(settings, profile);
  const root = normalizeFolder(resolved.rootFolder);
  return baseConfig(
    `${root}/Tasks`,
    taskBaseProperties(),
    sprintView(resolved.id, 'Sprint board', 'kanban'),
    {
      task_state: 'if(note["is done"], "Done", if(note["in progress"], "In progress", "Not started"))',
    },
  );
}

function definitionsForProfile(settings: SprintSettings, profile: SprintProfile): BaseDefinition[] {
  const resolved = resolveSprintProfile(settings, profile);
  const root = normalizeFolder(resolved.rootFolder);
  if (!root) throw new Error(`Set a project folder for ${resolved.name || 'this sprint profile'}.`);

  const tasksBase = basePath(resolved.tasksBasePath || `${root}/Bases/Tasks.base`);
  const sprintsBase = basePath(resolved.sprintsBasePath || `${root}/Bases/Sprints.base`);
  const projectsBase = basePath(resolved.projectsBasePath || `${root}/Bases/Projects.base`);

  return [
    {
      path: tasksBase,
      folder: `${root}/Tasks`,
      content: tasksBaseContent(settings, profile, true),
    },
    {
      path: sprintsBase,
      folder: `${root}/Sprints`,
      content: baseConfig(
        `${root}/Sprints`,
        {
          'file.name': 'Sprint',
          'note.sprint number': 'Number',
          'note.start date': 'Start',
          'note.end date': 'End',
          'note.sprint status': 'Status',
          'note.review': 'Review',
          'note.retrospective': 'Retrospective',
        },
        [
          ...sprintOverviewView(resolved.id),
          '  - type: table',
          '    name: "Active sprints"',
          '    filters:',
          '      or:',
          '        - note["sprint status"] == "current"',
          '        - note["sprint status"] == "next"',
          '        - note["sprint status"] == "last"',
          '    order:',
          ...[
            'file.name',
            'sprint status',
            'start date',
            'end date',
            'formula.planned',
            'formula.velocity',
            'review',
            'retrospective',
          ].map((property) => `      - ${property}`),
          '    sort:',
          '      - property: start date',
          '        direction: DESC',
          `  - type: ${SPRINT_VELOCITY_VIEW_TYPE}`,
          '    name: "Velocity"',
          `    sprintProfile: ${yamlString(resolved.id)}`,
          '  - type: table',
          '    name: "All sprints"',
          '    order:',
          ...[
            'file.name',
            'sprint status',
            'start date',
            'end date',
            'formula.nth_sprint',
            'formula.planned',
            'formula.velocity',
            'review',
            'retrospective',
          ].map((property) => `      - ${property}`),
          '    sort:',
          '      - property: start date',
          '        direction: DESC',
          '    columnSize:',
          '      formula.nth_sprint: 100',
          '      formula.velocity: 86',
        ],
        {
          nth_sprint: 'number(file.name.split(" ")[1])',
          velocity: 'file.backlinks.filter(value.asFile().properties["is done"]).map(value.asFile().properties.estimate).reduce(acc + value, 0)',
          planned: 'file.backlinks.map(value.asFile().properties.estimate).reduce(acc + value, 0)',
        },
      ),
    },
    {
      path: projectsBase,
      folder: `${root}/Projects`,
      content: baseConfig(
        `${root}/Projects`,
        {
          'file.name': 'Project',
          'formula.project_state': 'State',
          'note.in progress': 'In progress',
          'note.is done': 'Done',
          'note.owner': 'Owner',
          'note.priority': 'Priority',
          'note.due': 'Due',
        },
        [
          ...tableView('Projects', [
            'file.name',
            'formula.project_state',
            'note.in progress',
            'note.is done',
            'note.owner',
            'note.priority',
            'note.due',
          ]),
        ],
        {
          project_state: 'if(note["is done"], "Done", if(note["in progress"], "In progress", "Not started"))',
        },
      ),
    },
  ];
}

export class SprintBaseGenerator {
  constructor(private readonly app: App) {}

  async generate(settings: SprintSettings): Promise<SprintBaseGenerationResult> {
    const result: SprintBaseGenerationResult = {
      created: 0,
      skipped: 0,
      profilesGenerated: 0,
    };

    for (const profile of settings.profiles.filter((candidate) => candidate.enabled)) {
      await this.withContext(`Migrate Tasks Base for ${profile.name || profile.id}`, () => (
        this.migrateTasksBase(settings, profile)
      ));
      await this.withContext(`Remove obsolete Sprint Board Base for ${profile.name || profile.id}`, () => (
        this.removeObsoleteSprintBoardBase(settings, profile)
      ));
      for (const definition of definitionsForProfile(settings, profile)) {
        await this.withContext(`Create Base ${definition.path}`, async () => {
          await this.ensureFolder(definition.folder);
          await this.ensureFolder(baseFolder(definition.path));
          if (this.app.vault.getAbstractFileByPath(definition.path)) {
            result.skipped += 1;
            return;
          }
          const created = await this.createBaseFile(definition.path, definition.content);
          if (created) result.created += 1;
          else result.skipped += 1;
        });
      }
      await this.withContext(`Create samples for ${profile.name || profile.id}`, () => (
        this.writeSampleNotes(settings, profile)
      ));
      await this.withContext(`Create dashboard for ${profile.name || profile.id}`, () => (
        this.writeDashboard(settings, profile)
      ));
      await this.withContext(`Write AI instructions for ${profile.name || profile.id}`, () => (
        this.writeProfileAgentInstructions(settings, profile)
      ));
      result.profilesGenerated += 1;
    }
    await this.withContext('Update vault-root AI instructions', () => (
      settings.generateVaultRootInstructions
        ? this.writeVaultRootAgentInstructions(settings)
        : this.removeVaultRootAgentInstructions()
    ));
    await this.withContext('Write Obsidian property types', () => this.writePropertyTypes());

    return result;
  }

  async resetProfileRoot(settings: SprintSettings, profileId: string): Promise<void> {
    const profile = settings.profiles.find((candidate) => candidate.id === profileId);
    if (!profile) throw new Error('Sprint profile not found.');
    const root = normalizeFolder(profile.rootFolder);
    if (!root) throw new Error(`Set a project folder for ${profile.name || 'this sprint profile'} before resetting.`);
    const existing = this.app.vault.getAbstractFileByPath(root);
    if (existing) await this.app.vault.delete(existing, true);
  }

  private async removeObsoleteSprintBoardBase(
    settings: SprintSettings,
    profile: SprintProfile,
  ): Promise<void> {
    const root = normalizeFolder(profile.rootFolder);
    if (!root) return;
    const path = `${root}/Bases/Sprint Board.base`;
    const existing = this.app.vault.getFileByPath(path);
    if (!existing) return;
    const current = await this.app.vault.read(existing);
    if (current === standaloneSprintBoardContent(settings, profile)) {
      await this.app.vault.delete(existing, true);
      return;
    }
    console.warn(`[Sprint] Kept customized obsolete Base for manual review: ${path}`);
  }

  private async migrateTasksBase(settings: SprintSettings, profile: SprintProfile): Promise<void> {
    const resolved = resolveSprintProfile(settings, profile);
    const path = basePath(resolved.tasksBasePath);
    const existing = this.app.vault.getFileByPath(path);
    if (!existing) return;
    const current = await this.app.vault.read(existing);
    if (current === tasksBaseContent(settings, profile, false)) {
      await this.app.vault.modify(existing, tasksBaseContent(settings, profile, true));
    }
  }

  private async ensureFolder(folder: string): Promise<void> {
    let current = '';
    for (const segment of normalizePath(folder).split('/').filter(Boolean)) {
      current = current ? `${current}/${segment}` : segment;
      const existing = this.app.vault.getAbstractFileByPath(current);
      if (existing) continue;
      try {
        await this.app.vault.createFolder(current);
      } catch (error) {
        if (!isAlreadyExistsError(error) && !this.app.vault.getAbstractFileByPath(current)) {
          throw error;
        }
      }
    }
  }

  private async writeProfileAgentInstructions(
    settings: SprintSettings,
    profile: SprintProfile,
  ): Promise<void> {
    const root = normalizeFolder(profile.rootFolder);
    if (!root) return;
    const instructions = sprintInstructions(settings, [profile]);
    await this.writeManagedFile(`${root}/AGENTS.md`, instructions);
    await this.writeManagedFile(`${root}/CLAUDE.md`, instructions);
    await this.writeOwnedFile(
      `${root}/.codex/skills/sprint/SKILL.md`,
      skillInstructions(settings, [profile]),
    );
    await this.writeOwnedFile(
      `${root}/.claude/skills/sprint/SKILL.md`,
      skillInstructions(settings, [profile]),
    );
  }

  private async writeVaultRootAgentInstructions(settings: SprintSettings): Promise<void> {
    await this.removeLegacyVaultRootSkills();
    await this.writeManagedFile('AGENTS.md', sprintInstructions(settings));
    await this.writeManagedFile('CLAUDE.md', sprintInstructions(settings));
  }

  private async removeVaultRootAgentInstructions(): Promise<void> {
    await this.removeManagedFile('AGENTS.md');
    await this.removeManagedFile('CLAUDE.md');
    await this.removeLegacyVaultRootSkills();
  }

  private async removeLegacyVaultRootSkills(): Promise<void> {
    await this.removeOwnedSkillFile('.codex/skills/sprint/SKILL.md');
    await this.removeOwnedSkillFile('.claude/skills/sprint/SKILL.md');
  }

  private async writePropertyTypes(): Promise<void> {
    const path = normalizePath(`${this.app.vault.configDir}/types.json`);
    const existing = await this.app.vault.adapter.exists(path)
      ? await this.app.vault.adapter.read(path)
      : '{}';
    const parsed = this.parseJsonObject(existing);
    const types = this.parseJsonObject(parsed.types);
    Object.assign(types, {
      estimate: 'number',
      'in progress': 'checkbox',
      'is done': 'checkbox',
      project: 'multitext',
      sprint: 'multitext',
      priority: 'number',
      owner: 'text',
      due: 'date',
      'due date': 'date',
    });
    parsed.types = types;
    await this.app.vault.adapter.write(path, `${JSON.stringify(parsed, null, 2)}\n`);
  }

  private async createBaseFile(path: string, content: string): Promise<boolean> {
    try {
      await this.app.vault.create(path, content);
      return true;
    } catch (error) {
      if (!isAlreadyExistsError(error) && !this.app.vault.getAbstractFileByPath(path)) {
        throw error;
      }
      return false;
    }
  }

  private async withContext<T>(label: string, operation: () => Promise<T>): Promise<T> {
    try {
      return await operation();
    } catch (error) {
      const detail = error instanceof Error ? error.message : String(error);
      throw new Error(`${label} failed: ${detail}`, { cause: error });
    }
  }

  private parseJsonObject(value: unknown): Record<string, unknown> {
    if (typeof value === 'string') {
      try {
        const parsed = JSON.parse(value) as unknown;
        return this.parseJsonObject(parsed);
      } catch {
        return {};
      }
    }
    return value && typeof value === 'object' && !Array.isArray(value)
      ? { ...value as Record<string, unknown> }
      : {};
  }

  private async writeSampleNotes(settings: SprintSettings, profile: SprintProfile): Promise<void> {
    const resolved = resolveSprintProfile(settings, profile);
    const root = normalizeFolder(resolved.rootFolder);
    if (!root) return;

    for (const note of this.sampleNotes(root)) {
      if (this.app.vault.getAbstractFileByPath(note.path)) continue;
      await this.writeFile(note.path, note.content);
    }
  }

  private sampleNotes(root: string): SampleNote[] {
    return [
      {
        path: `${root}/Projects/Welcome to Agile PM.md`,
        content: frontmatterNote(
          [
            'priority: 1',
            'in progress: true',
            'is done: false',
            'owner: "You"',
          ],
          [
            '# Welcome to Agile PM',
            '',
            'Use this project to learn the workflow. Projects collect related task notes and help you see what each sprint supports.',
            '',
            'Try opening the Projects Base, then replace this tutorial project after you create your first real project.',
          ].join('\n'),
        ),
      },
      {
        path: `${root}/Projects/Sprint system setup.md`,
        content: frontmatterNote(
          [
            'priority: 2',
            'in progress: false',
            'is done: false',
            'owner: "You"',
          ],
          [
            '# Sprint system setup',
            '',
            'This sample project groups the tutorial tasks that explain how to plan, execute, and review sprint work.',
          ].join('\n'),
        ),
      },
      {
        path: `${root}/Tasks/Review the Agile PM dashboard.md`,
        content: frontmatterNote(
          [
            'estimate: 1',
            'in progress: false',
            'is done: false',
            'project:',
            '  - "[[Welcome to Agile PM]]"',
          ],
          [
            '# Review the Agile PM dashboard',
            '',
            'Open the dashboard note at the top of this folder and inspect the current tasks, Velocity chart, current sprint scope, and Projects view.',
          ].join('\n'),
        ),
      },
      {
        path: `${root}/Tasks/Add your first real task.md`,
        content: frontmatterNote(
          [
            'estimate: 2',
            'in progress: false',
            'is done: false',
            'project:',
            '  - "[[Welcome to Agile PM]]"',
          ],
          [
            '# Add your first real task',
            '',
            'Create a task note in the Tasks folder. Give it an estimate, connect it to a project, and leave `sprint` empty until you are ready to plan it.',
          ].join('\n'),
        ),
      },
      {
        path: `${root}/Tasks/Plan work into the current sprint.md`,
        content: frontmatterNote(
          [
            'estimate: 3',
            'in progress: true',
            'is done: false',
            'project:',
            '  - "[[Sprint system setup]]"',
          ],
          [
            '# Plan work into the current sprint',
            '',
            'Use the Tasks Base to assign a task to the generated current sprint. Sprint creates sprint notes and keeps their status metadata synchronized.',
          ].join('\n'),
        ),
      },
      {
        path: `${root}/Tasks/Mark a task complete.md`,
        content: frontmatterNote(
          [
            'estimate: 1',
            'in progress: false',
            'is done: true',
            'project:',
            '  - "[[Sprint system setup]]"',
          ],
          [
            '# Mark a task complete',
            '',
            'Set `is done` to true when the task is finished. Completed estimates contribute to the Velocity view in the Sprints Base.',
          ].join('\n'),
        ),
      },
      {
        path: `${root}/Tasks/Write a sprint review.md`,
        content: frontmatterNote(
          [
            'estimate: 2',
            'in progress: false',
            'is done: false',
            'project:',
            '  - "[[Sprint system setup]]"',
          ],
          [
            '# Write a sprint review',
            '',
            'At the end of a sprint, summarize outcomes in the generated sprint note. Keep retrospectives concrete and action-oriented.',
          ].join('\n'),
        ),
      },
    ];
  }

  private async writeDashboard(settings: SprintSettings, profile: SprintProfile): Promise<void> {
    const resolved = resolveSprintProfile(settings, profile);
    const root = normalizeFolder(resolved.rootFolder);
    if (!root) return;

    await this.ensureFolder(root);
    const title = root.split('/').at(-1) || resolved.name || 'Agile PM';
    const dashboardPath = `${root}/${title}.md`;
    const sprints = this.readSprints(`${root}/Sprints`);
    const tasks = this.readTasks(`${root}/Tasks`);
    const current = sprints.find((sprint) => sprint.status === 'current') ?? null;
    const currentTasks = current
      ? tasks.filter((task) => sprintReferences(task.sprint, current.name))
      : [];
    const incompleteCurrentTasks = currentTasks.filter((task) => !task.done);
    const taskLines = incompleteCurrentTasks.length > 0
      ? incompleteCurrentTasks.map((task) => `- [ ] ${linkTo(task.path, task.name)}${task.estimate ? ` (${task.estimate})` : ''}`)
      : ['- No open tasks assigned to the current sprint.'];

    const content = [
      '## Current Sprint',
      '',
      current
        ? `Current sprint: ${linkTo(current.path, current.name)} (${current.startDate ?? 'unknown'} to ${current.endDate ?? 'unknown'})`
        : 'No current sprint has been generated yet.',
      '',
      '## Current Tasks',
      '',
      ...taskLines,
      '',
      `![[${resolved.tasksBasePath}#Sprint board]]`,
      '',
      '## Velocity',
      '',
      `![[${resolved.sprintsBasePath}#Velocity]]`,
      '',
      '## Projects',
      '',
      `![[${resolved.projectsBasePath}#Projects]]`,
      '',
    ].join('\n');

    await this.writeFile(dashboardPath, `# ${title}\n\n${content}`);
  }

  private readSprints(folder: string): SprintSummary[] {
    const prefix = `${normalizeFolder(folder)}/`;
    return this.app.vault.getMarkdownFiles()
      .filter((file) => file.path.startsWith(prefix) && !file.path.slice(prefix.length).includes('/'))
      .map((file) => {
        const frontmatter = this.getFrontmatter(file);
        return {
          name: file.basename,
          path: file.path,
          startDate: readDate(frontmatter['start date']),
          endDate: readDate(frontmatter['end date']),
          status: typeof frontmatter['sprint status'] === 'string' ? frontmatter['sprint status'] : null,
        };
      });
  }

  private readTasks(folder: string): TaskSummary[] {
    const prefix = `${normalizeFolder(folder)}/`;
    return this.app.vault.getMarkdownFiles()
      .filter((file) => file.path.startsWith(prefix) && !file.path.slice(prefix.length).includes('/'))
      .map((file) => {
        const frontmatter = this.getFrontmatter(file);
        return {
          name: file.basename,
          path: file.path,
          sprint: frontmatter.sprint,
          estimate: numericEstimate(frontmatter.estimate),
          done: isTaskDone(frontmatter),
        };
      });
  }

  private getFrontmatter(file: TFile): Record<string, unknown> {
    return { ...(this.app.metadataCache.getFileCache(file)?.frontmatter ?? {}) };
  }

  private async writeManagedFile(path: string, content: string, initialContent = ''): Promise<void> {
    const existing = this.app.vault.getFileByPath(path);
    if (!existing) {
      await this.writeFile(path, `${initialContent}${managedContent(content)}`);
      return;
    }
    const current = await this.app.vault.read(existing);
    if (!current.includes(MANAGED_START) || !current.includes(MANAGED_END)) {
      console.warn(`[Sprint] Skipped existing AI instruction file not managed by Sprint: ${path}`);
      return;
    }
    await this.app.vault.modify(existing, replaceManagedSection(current, content));
  }

  private async removeManagedFile(path: string): Promise<void> {
    const existing = this.app.vault.getFileByPath(path);
    if (!existing) return;
    const current = await this.app.vault.read(existing);
    const start = current.indexOf(MANAGED_START);
    const end = current.indexOf(MANAGED_END);
    if (start === -1 || end === -1 || end < start) return;
    const remaining = `${current.slice(0, start)}${current.slice(end + MANAGED_END.length)}`.trim();
    if (!remaining) {
      await this.app.vault.delete(existing, true);
      return;
    }
    await this.app.vault.modify(existing, `${remaining}\n`);
  }

  private async writeOwnedFile(path: string, content: string): Promise<void> {
    await this.ensureFolder(baseFolder(path));
    const existing = this.app.vault.getFileByPath(path);
    if (!existing) {
      await this.writeFile(path, content);
      return;
    }
    const current = await this.app.vault.read(existing);
    if (!current.includes(GENERATED_FILE_MARKER)) {
      console.warn(`[Sprint] Skipped existing AI skill file not managed by Sprint: ${path}`);
      return;
    }
    await this.app.vault.modify(existing, content);
  }

  private async removeOwnedSkillFile(path: string): Promise<void> {
    const existing = this.app.vault.getFileByPath(path);
    if (!existing) return;
    const current = await this.app.vault.read(existing);
    const isSprintGenerated = current.includes(GENERATED_FILE_MARKER) || (
      current.includes('name: sprint-vault')
      && current.includes('These instructions are generated by the Sprint Obsidian plugin')
    );
    if (isSprintGenerated) await this.app.vault.delete(existing, true);
  }

  private async writeFile(path: string, content: string): Promise<void> {
    await this.ensureFolder(baseFolder(path));
    const existing = this.app.vault.getFileByPath(path);
    if (existing) {
      await this.app.vault.modify(existing, content);
      return;
    }
    try {
      await this.app.vault.create(path, content);
    } catch (error) {
      if (!isAlreadyExistsError(error)) throw error;
      const raced = this.app.vault.getFileByPath(path);
      if (!raced) throw error;
      await this.app.vault.modify(raced, content);
    }
  }
}
